In [2]:
# yolo v8 체크
import ultralytics

ultralytics.checks()

Ultralytics YOLOv8.0.119  Python-3.9.16 torch-1.8.0 CUDA:0 (NVIDIA GeForce RTX 3070, 8192MiB)
Setup complete  (20 CPUs, 15.7 GB RAM, 433.4/476.3 GB disk)


In [3]:
# GPU 디바이스 네임 체크
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 5006556690623047243
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 5719982080
locality {
  bus_id: 1
  links {
  }
}
incarnation: 3530081591389139966
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3070, pci bus id: 0000:01:00.0, compute capability: 8.6"
xla_global_id: 416903419
]


In [3]:
# GPU 활용 가능 여부 확인
import torch

print(torch.cuda.get_device_name(0))
print(torch.cuda.is_available())

NVIDIA GeForce RTX 3070
True


In [2]:
# yolo 최초 모델 설정
from ultralytics import YOLO as yolo

ultralytics_model = yolo('yolov8n.pt')

print(type(ultralytics_model.names), len(ultralytics_model.names))
print(ultralytics_model.names)

<class 'dict'> 80
{0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell p

In [12]:
# 고해상도 데이터 학습
import os
from ultralytics import YOLO as yolo

os.environ['KMP_DUPLICATE_LIB_OK']='True'

model = yolo('C:/Users/user/Desktop/WORK/DBUG/runs/detect/train20/weights/best.pt')
model.train(data='D:/InsectData/convertData/HighDefinition_data/HD_data.yaml', epochs=30, verbose=True, workers=0)

New https://pypi.org/project/ultralytics/8.0.120 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.119  Python-3.9.16 torch-1.8.0 CUDA:0 (NVIDIA GeForce RTX 3070, 8192MiB)
WARNING  Upgrade to torch>=2.0.0 for deterministic training.
yolo\engine\trainer: task=detect, mode=train, model=C:/Users/user/Desktop/WORK/DBUG/runs/detect/train20/weights/best.pt, data=D:/InsectData/convertData/HighDefinition_data/HD_data.yaml, epochs=30, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_con

In [9]:
# 2번 카메라 데이터 학습
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

# model = yolo('C:/Users/User/Desktop/InsectData/runs/detect/고해상도데이터best.pt/weights/best.pt')
ultralytics_model=yolo('C:/Users/user/Desktop/WORK/DBUG/runs/detect/train19/weights/best.pt')
ultralytics_model.train(data='D:/InsectData/convertData/Cam2_data/cam2_data.yaml', workers=0, epochs=30)

New https://pypi.org/project/ultralytics/8.0.120 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.119  Python-3.9.16 torch-1.8.0 CUDA:0 (NVIDIA GeForce RTX 3070, 8192MiB)
WARNING  Upgrade to torch>=2.0.0 for deterministic training.
yolo\engine\trainer: task=detect, mode=train, model=C:/Users/user/Desktop/WORK/DBUG/runs/detect/train19/weights/best.pt, data=D:/InsectData/convertData/Cam2_data/cam2_data.yaml, epochs=30, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False,

In [11]:
# 예측시켜보기
from ultralytics import YOLO as yolo

model = yolo('C:/Users/user/Desktop/WORK/DBUG/runs/detect/train20/weights/best.pt')
# ultralytics_model.predict(source="D:/InsectData/data/Training/rawData/TS1/PtecticusTenebrifer/Caterpillar/HighDefinition/Capture_20211115_15_27_35.jpg", show=False, conf=0.5, save=True)
# ultralytics_model.predict(source='D:/InsectData/data/Validation/rawData/VS1/PtecticusTenebrifer/Caterpillar/Cam2/Capture_20211110_09_22_04.jpg', conf=0.5, save=True)
# ultralytics_model.predict(source='D:/InsectData/data/Validation/rawData/VS1/PtecticusTenebrifer/Caterpillar/HighDefinition/Capture_20211204_02_12_11.jpg', conf=0.5, save=True)

# model.predict(source="D:/InsectData/data/Validation/rawData/VS1/PtecticusTenebrifer/Caterpillar/HighDefinition/Capture_20211204_12_13_41.jpg", show=False, conf=0.5, save=True)
model.predict(source='D:/InsectData/data/Training/rawData/TS1/PtecticusTenebrifer/Caterpillar/Cam3/Capture_20211109_15_49_37.jpg', save=True, conf=0.5)


image 1/1 D:\InsectData\data\Training\rawData\TS1\PtecticusTenebrifer\Caterpillar\Cam3\Capture_20211109_15_49_37.jpg: 384x640 5 bugs, 14.0ms
Speed: 1.0ms preprocess, 14.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs\detect\predict8


[ultralytics.yolo.engine.results.Results object with attributes:
 
 boxes: ultralytics.yolo.engine.results.Boxes object
 keypoints: None
 keys: ['boxes']
 masks: None
 names: {0: 'bug'}
 orig_img: array([[[17, 32, 28],
         [24, 39, 35],
         [29, 44, 40],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        [[19, 34, 30],
         [25, 40, 36],
         [30, 45, 41],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        [[21, 36, 32],
         [27, 42, 38],
         [30, 45, 41],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        ...,
 
        [[29, 44, 40],
         [30, 45, 41],
         [29, 44, 40],
         ...,
         [ 0,  0,  1],
         [ 0,  0,  1],
         [ 0,  0,  1]],
 
        [[29, 44, 40],
         [29, 44, 40],
         [28, 43, 39],
         ...,
         [ 0,  0,  1],
         [ 0,  0,  1],
         [ 0,  0,  1]],
 
        [[28, 

In [10]:
# model = ultralytics_model.model
# model = model.cuda()
dummy_input = torch.randn(1, 3, 416, 416, device='cuda')
best = "C:/Users/user/Desktop/WORK/DBUG/runs/detect/train16/weights/best.pt"
torch.onnx.export(best, dummy_input, "D:/InsectData/data/model.onnx")

AttributeError: 'str' object has no attribute 'training'

In [11]:
import torch

# 학습된 가중치 로드
# weights = 'C:/Users/User/Desktop/InsectData/runs/detect/train36/weights/best.pt'
# chkpt = torch.load(weights, map_location=torch.device('cpu'))
# model = ultralytics_model(cfg=chkpt['model'].yaml, ch=3, nc=chkpt['model'].nc)  # nc is the number of classes
# model.load_state_dict(chkpt['model'].float().state_dict())  # load model weights

model = yolo('C:/Users/user/Desktop/WORK/DBUG/runs/detect/train16/weights/best.pt')

# ONNX로 변환
dummy_input = torch.randn(1, 3, 416, 416, device='cuda')
output = model(dummy_input)
model = model.model.cuda()
torch.onnx.export(model, dummy_input, "D:/InsectData/data/model.onnx")
# print(output.shape)


7.0ms


In [13]:
import onnx

# ONNX 모델 로드
model = onnx.load('D:/InsectData/data/model.onnx')

# 입력 레이어 출력
print('Model Input Layer:')
for input in model.graph.input:
    print(input.name, end=': ')
    # 레이어의 형상 출력
    shape = [dim.dim_value for dim in input.type.tensor_type.shape.dim]
    print(shape)


Model Input Layer:
input.1: [1, 3, 416, 416]


In [ ]:
import cv2
import numpy as np

# ONNX 모델 불러오기
net = cv2.dnn.readNetFromONNX('D:/InsectData/data/model.onnx')

# 이미지 불러오기
image = cv2.imread('D:/InsectData/data/Validation/rawData/VS1/PtecticusTenebrifer/Caterpillar/HighDefinition/Capture_20211117_13_45_52.jpg')

# 전처리 (이미지 크기 조절 및 정규화)
blob = cv2.dnn.blobFromImage(image, scalefactor=1/255.0, size=(416, 416), swapRB=True, crop=False)
net.setInput(blob)

# 모델 실행
outputs = net.forward()

# 결과 처리
for detection in outputs[0, 0, :, :]:
    confidence = float(detection[2])
    if confidence > 0.5:
        left = int(detection[3] * image.shape[1])
        top = int(detection[4] * image.shape[0])
        right = int(detection[5] * image.shape[1])
        bottom = int(detection[6] * image.shape[0])
        cv2.rectangle(image, (left, top), (right, bottom), (255, 0, 0), 2)
cv2.imshow("image", image)
cv2.waitKey(0)


In [17]:
import cv2
import numpy as np
import onnxruntime

classes = []

# 클래스 라벨 불러오기
with open("D:/InsectData/convertData/HighDefinition_data/classes.txt", "r") as f:
    classes = [line.strip() for line in f.readlines()]

# ONNX 런타임 세션 생성
sess = onnxruntime.InferenceSession("D:/InsectData/data/model.onnx")

# 이미지 불러오기
image = cv2.imread("D:/InsectData/data/Validation/rawData/VS1/PtecticusTenebrifer/Caterpillar/HighDefinition/Capture_20211117_13_45_52.jpg")
image = cv2.resize(image, None, fx=0.4, fy=0.4)
height, width, channels = image.shape
colors = np.random.uniform(0, 255, 3)

# 이미지 전처리
blob = cv2.dnn.blobFromImage(image, 0.00392, (416, 416), (0, 0, 0), swapRB=True, crop=False)
blob = blob.transpose((0, 1, 2, 3))  # ONNX는 CHW가 아니라 HWC 포맷을 기대

# 모델 실행 및 출력 얻기
input_name = sess.get_inputs()[0].name
output_name = sess.get_outputs()[0].name
outs = sess.run([output_name],{input_name: blob})

print(input_name)
print(output_name)
print(np.array(outs).shape)

for i, out in enumerate(outs):
    print(f"Output node {i} shape: {out.shape}")
    print(out)

# 결과 처리
class_ids = []
confidences = []
boxes = []

# 각 출력 노드에 대해 반복
for out in outs:
    # 첫 번째 차원(1)은 배치 크기를 나타내므로 우리는 이를 무시
    # 모든 그리드 셀에 대해 순회
    for grid in out[0]:
        # 바운딩 박스의 x, y 좌표, 너비, 높이, 그리고 객체 존재 확률을 추출
        center_x, center_y, w, h, objectness = grid[:5]

        # 객체 존재 확률이 0.5보다 크면, 해당 그리드 셀에 대한 예측을 저장
        if objectness > 0.1:
            # 이미지의 크기에 따라 바운딩 박스의 좌표와 크기를 스케일링
            center_x = int(center_x * image.shape[1])
            center_y = int(center_y * image.shape[0])
            w = int(w * image.shape[1])
            h = int(h * image.shape[0])

            # 바운딩 박스의 좌표를 계산 (YOLO는 바운딩 박스의 중심 좌표를 예측하므로, 이를 바운딩 박스의 좌측 상단 좌표로 변환해야 함)
            x = int(center_x - w / 2)
            y = int(center_y - h / 2)

            boxes.append([x, y, w, h])
            confidences.append(float(objectness))

            # 객체의 클래스 ID를 찾기 위해, 나머지 값을 확률로 간주하고 이 중에서 가장 높은 확률을 가진 클래스를 선택
            # 나머지 값을 확률로 간주하고 이 중에서 가장 높은 확률을 가진 클래스를 선택
            class_probabilities = grid[5:]
            class_id = np.argmax(class_probabilities)
            class_ids.append(class_id)
            # classes 리스트의 길이를 초과하지 않는지 확인
            # if class_id < len(classes):
            #     class_ids.append(class_id)
            # else:
            #     print(f"Warning: Predicted class id {class_id} is out of range of classes list with length {len(classes)}. Ignoring this box.")


# for out in outs:
#     for detection in out:
#         scores = detection[5:]
#         class_id = np.argmax(scores)
#         confidence = scores[class_id]
#         if confidence > 0.5:
#             # Object detected
#             center_x = int(detection[0] * width)
#             center_y = int(detection[1] * height)
#             w = int(detection[2] * width)
#             h = int(detection[3] * height)
#             # 좌표
#             x = int(center_x - w / 2)
#             y = int(center_y - h / 2)
#             boxes.append([x, y, w, h])
#             confidences.append(float(confidence))
#             class_ids.append(class_id)

# Non-Maxima Suppression 사용하여 겹치는 박스 제거
if boxes and confidences:  # 리스트가 비어 있지 않은지 확인
    indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
    print(indexes)
else:
    indexes = []

# 감지된 객체에 바운딩 박스와 레이블 그리기
font = cv2.FONT_HERSHEY_PLAIN
for i in range(len(boxes)):
    if i in indexes:
        x, y, w, h = boxes[i]
        label = str(class_ids[i])
        color = colors[0]
        cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)
        cv2.putText(image, label, (x, y + 30), font, 3, color, 3)
cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


input.1
420
(1, 1, 5, 3549)
Output node 0 shape: (1, 5, 3549)
[[[     8.9716      16.231      29.283 ...      333.75      365.82      394.58]
  [     5.6496      5.5761      5.4086 ...      400.05      400.03      400.15]
  [      16.34      30.702      56.936 ...      46.642      44.088      52.773]
  [     9.3943      9.6893      10.362 ...      19.935      20.346      27.208]
  [ 5.9307e-06  4.8876e-06  6.5565e-07 ...  3.0071e-05  3.3528e-05  3.4481e-05]]]
[2 0 3 1]


In [18]:
import cv2
import numpy as np

# ONNX 모델 로드
net = cv2.dnn.readNetFromONNX("C:/Users/User/Desktop/InsectData/runs/detect/train31/weights/best.onnx")

classes = []
with open("C:/Users/User/Desktop/InsectData/ConvertData/HighDefinition_data/labels/classes.txt", "r") as f:
    classes = [line.strip() for line in f.readlines()]

colors = np.random.uniform(0, 255, size=(len(classes), 3))

# 이미지 로드
image = cv2.imread("C:/Users/User/Desktop/InsectData/Data/Training/rawData/TS1/PtecticusTenebrifer/Caterpillar/Cam3/Capture_20211109_15_49_04.jpg")

# 이미지 크기 조정
image = cv2.resize(image, (640, 640))

blob = cv2.dnn.blobFromImage(image, 1.0/255.0, (416, 416), (0, 0, 0), swapRB=True, crop=False)

net.setInput(blob)
outs = net.forward()

class_ids = []
confidences = []
boxes = []

for out in outs:
    for detection in out:
        scores = detection[5:]
        class_id = np.argmax(scores)
        confidence = scores[class_id]

        # 신뢰도 임계값 설정 (예: 0.5)
        if confidence > 0.5:
            center_x = int(detection[0] * image.shape[1])
            center_y = int(detection[1] * image.shape[0])
            w = int(detection[2] * image.shape[1])
            h = int(detection[3] * image.shape[0])

            x = int(center_x - w / 2)
            y = int(center_y - h / 2)

            boxes.append([x, y, w, h])
            confidences.append(float(confidence))
            class_ids.append(class_id)

indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
font = cv2.FONT_HERSHEY_PLAIN

for i in range(len(boxes)):
    if i in indexes:
        x, y, w, h = boxes[i]
        label = str(classes[class_ids[i]])
        color = colors[i]
        cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)
        cv2.putText(image, label, (x, y + 30), font, 3, color, 3)

cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\reshape_layer.cpp:150: error: (-1:Backtrace) Can't infer a dim denoted by -1 in function 'cv::dnn::computeShapeByReshapeMask'


In [1]:
import cv2
import urllib.request
import numpy as np

url = 'http://192.168.0.46:8888/stream'
cv2.namedWindow("Live Cam", cv2.WINDOW_AUTOSIZE)

cap = cv2.VideoCapture(url)

if not cap.isOpened():
    print("Failed to Open the IP camera Stream")
    exit()

while True:
    img_resp = urllib.request.urlopen(url)
    imgnp = np.array(bytearray(img_resp.read()), dtype=np.uint8)

    im = cv2.imdecode(imgnp, -1)

    cv2.imshow("Live Cam", im)
    key=cv2.waitKey(5)
    if key==ord('q'): break

cap.release()
cv2.destroyAllWindows()

: 

: 

In [1]:
import cv2
import numpy as np
from ultralytics import YOLO

model = YOLO('yolov8n.pt')

url = f'http://192.168.0.46:8888/stream'
cap = cv2.VideoCapture(url)

if not cap.isOpened():
    print("Failed to Open the IP camera Stream")
    exit()

while cap.isOpened():
    success, frame = cap.read()

    if success:
        results = model(frame)
        annotated_frame = results[0].plot()

        cv2.imshow("YOLOv8 Inference", annotated_frame)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    
    else:
        break

cap.release()
cv2.destroyAllWindows()

c:\Users\user\anaconda3\envs\DBUG\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|██████████| 6.23M/6.23M [00:00<00:00, 7.09MB/s]

0: 480x640 (no detections), 9.0ms
Speed: 2.0ms preprocess, 9.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 (no detections), 5.0ms
Speed: 1.0ms preprocess, 5.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 (no detections), 5.0ms
Speed: 3.0ms preprocess, 5.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 (no detections), 5.0ms
Speed: 2.0ms preprocess, 5.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 (no detections), 5.0ms
Speed: 1.0ms preprocess, 5.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

0: 480x640 (no detections), 5.2ms


AttributeError: module 'cv2' has no attribute 'destroAllWindows'

: 

In [1]:
import cv2
from urllib.request import Request, urlopen
import numpy as np

stream = urlopen('http://192.168.0.46:8888/stream')
bytes = b''
while True:
    bytes += stream.read(1024)
    a = bytes.find(b'\xff\xd8')
    b = bytes.find(b'\xff\xd9')
    if a != -1 and b != -1:
        jpg = bytes[a:b+2]
        bytes = bytes[b+2:]
        i = cv2.imdecode(np.fromstring(jpg, dtype=np.uint8), cv2.IMREAD_COLOR)
        cv2.imshow('i', i)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

C:\Users\user\AppData\Local\Temp\ipykernel_7456\1131349563.py:14: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  i = cv2.imdecode(np.fromstring(jpg, dtype=np.uint8), cv2.IMREAD_COLOR)


error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:798: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'


: 