In [1]:
# yolo v8 체크
import ultralytics

ultralytics.checks()

Ultralytics YOLOv8.0.117  Python-3.9.16 torch-1.8.0 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 8192MiB)
Setup complete  (24 CPUs, 31.9 GB RAM, 616.9/903.5 GB disk)


In [2]:
# GPU 디바이스 네임 체크
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 4211980399169004211
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 5762973696
locality {
  bus_id: 1
  links {
  }
}
incarnation: 10849621960162805192
physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 3060 Ti, pci bus id: 0000:2b:00.0, compute capability: 8.6"
xla_global_id: 416903419
]


In [1]:
# yolo 최초 모델 설정
from ultralytics import YOLO as yolo

ultralytics_model = yolo('yolov8n.pt')

print(type(ultralytics_model.names), len(ultralytics_model.names))
print(ultralytics_model.names)

  0%|          | 0.00/6.23M [00:00<?, ?B/s]

<class 'dict'> 80
{0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell p

In [3]:
from ultralytics import YOLO as yolo

model = yolo('yolov8n-seg.pt')

model.track(source='https://youtu.be/Zgi9g1ksQHc', show=True)


1/1: https://youtu.be/Zgi9g1ksQHc... Success  (6557 frames of shape 1280x676 at 24.00 FPS)


    WARNING  stream/video/webcam/dir predict source will accumulate results in RAM unless `stream=True` is passed,
    causing potential out-of-memory errors for large sources or long-running streams/videos.

    Usage:
        results = model(source=..., stream=True)  # generator of Results objects
        for r in results:
            boxes = r.boxes  # Boxes object for bbox outputs
            masks = r.masks  # Masks object for segment masks outputs
            probs = r.probs  # Class probabilities for classification outputs

0: 352x640 2 cars, 33.0ms
0: 352x640 2 cars, 29.0ms
0: 352x640 2 cars, 9.0ms
0: 352x640 2 cars, 13.0ms
0: 352x640 1 car, 9.0ms
0: 352x640 1 car, 10.0ms
0: 352x640 1 car, 11.0ms
0: 352x640 1 car, 10.0ms
0: 352x640 1 car, 12.0ms
0: 352x640 1 car, 11.0ms
0: 352x640 1 car, 9.0ms
0: 352x640 1 car, 11.0ms
0: 352x640 1 car, 9.0ms
0: 352x640 1 car, 9.5ms
0: 352x640 1 car, 10

[ultralytics.yolo.engine.results.Results object with attributes:
 
 boxes: ultralytics.yolo.engine.results.Boxes object
 keypoints: None
 keys: ['boxes', 'masks']
 masks: ultralytics.yolo.engine.results.Masks object
 names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 5

In [4]:
# GPU 활용 가능 여부 확인
import torch

print(torch.cuda.get_device_name(0))
print(torch.cuda.is_available())

NVIDIA GeForce RTX 3060 Ti
True


In [1]:
from ultralytics import YOLO
model = YOLO('yolov8n.pt')

model.export(format='tfjs')

Ultralytics YOLOv8.0.117  Python-3.9.16 torch-1.8.0 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

PyTorch: starting from yolov8n.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)
requirements: Ultralytics requirements "onnx2tf>=1.7.7" "sng4onnx>=1.0.1" "onnxsim>=0.4.17" "onnx_graphsurgeon>=0.3.26" "tflite_support" not found, attempting AutoUpdate...
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
     -------------------------------------- 367.8/367.8 kB 3.8 MB/s eta 0:00:00
     ---------------------------------------- 1.2/1.2 MB 15.8 MB/s eta 0:00:00
     ---------------------------------------- 42.1/42.1 kB 2.0 MB/s eta 0:00:00
     ------------------------------------- 469.6/469.6 kB 28.7 MB/s eta 0:00:00
     ---------------------------------------- 239.4/239.4 kB ? eta 0:00:00
     ---------------------------------------- 199.7/199.7 kB ? eta 0:00:00
     --------------------------------------

[]

In [5]:
# 고해상도 데이터 학습
model = yolo('yolov8n-seg.pt')
model.train(data='C:/Users/User/Desktop/InsectData/ConvertData/HighDefinition_data/HD_data.yaml', epochs=10, verbose=True, workers=0)

New https://pypi.org/project/ultralytics/8.0.120 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.117  Python-3.9.16 torch-1.8.0 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 8192MiB)
WARNING  Upgrade to torch>=2.0.0 for deterministic training.
yolo\engine\trainer: task=segment, mode=train, model=yolov8n-seg.pt, data=C:/Users/User/Desktop/InsectData/ConvertData/HighDefinition_data/HD_data.yaml, epochs=10, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=None, exist_ok=False, pretrained=False, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, sho

TypeError: ERROR ❌ segment dataset incorrectly formatted or not a segment dataset.
This error can occur when incorrectly training a 'segment' model on a 'detect' dataset, i.e. 'yolo train model=yolov8n-seg.pt data=coco128.yaml'.
Verify your dataset is a correctly formatted 'segment' dataset using 'data=coco128-seg.yaml' as an example.
See https://docs.ultralytics.com/tasks/segment/ for help.

WARNING  Video stream unresponsive, please check your IP camera connection.
WARNING  Video stream unresponsive, please check your IP camera connection.
WARNING  Video stream unresponsive, please check your IP camera connection.


In [6]:
# 2번 카메라 데이터 학습
# model = yolo('C:/Users/User/Desktop/InsectData/runs/detect/고해상도데이터best.pt/weights/best.pt')
ultralytics_model.train(data='C:/Users/User/Desktop/InsectData/ConvertData/Cam2_data/cam2_data.yaml', workers=0, epochs=10)

New https://pypi.org/project/ultralytics/8.0.119 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.117  Python-3.9.16 torch-1.8.0 CUDA:0 (NVIDIA GeForce RTX 3060 Ti, 8192MiB)
WARNING  Upgrade to torch>=2.0.0 for deterministic training.
yolo\engine\trainer: task=detect, mode=train, model=yolov8s.pt, data=C:/Users/User/Desktop/InsectData/ConvertData/Cam2_data/cam2_data.yaml, epochs=10, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=0, project=None, name=None, exist_ok=False, pretrained=False, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True

In [2]:
model = yolo('C:/Users/User/Desktop/InsectData/runs/detect/train36/weights/best.pt')
model.predict(source="C:/Users/User/Desktop/InsectData/Data/Training/rawData/TS1/PtecticusTenebrifer/Caterpillar/HighDefinition/Capture_20211115_15_27_37.jpg", save=True, conf=0.5)


image 1/1 C:\Users\User\Desktop\InsectData\Data\Training\rawData\TS1\PtecticusTenebrifer\Caterpillar\HighDefinition\Capture_20211115_15_27_37.jpg: 384x640 11 bugs, 19.0ms
Speed: 3.0ms preprocess, 19.0ms inference, 18.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs\detect\predict


[ultralytics.yolo.engine.results.Results object with attributes:
 
 boxes: ultralytics.yolo.engine.results.Boxes object
 keypoints: None
 keys: ['boxes']
 masks: None
 names: {0: 'bug'}
 orig_img: array([[[ 0,  2,  0],
         [ 0,  1,  0],
         [ 0,  0,  0],
         ...,
         [80, 85, 64],
         [82, 87, 66],
         [86, 91, 70]],
 
        [[ 0,  2,  0],
         [ 0,  1,  0],
         [ 0,  0,  0],
         ...,
         [83, 88, 67],
         [84, 89, 68],
         [85, 90, 69]],
 
        [[ 0,  2,  0],
         [ 0,  1,  0],
         [ 0,  0,  0],
         ...,
         [87, 92, 71],
         [86, 91, 70],
         [85, 90, 69]],
 
        ...,
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [13, 25,  3],
         [10, 22,  0],
         [ 9, 21,  0]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 4, 16,  0],
         [ 4, 16,  0],
         [ 5, 17,  0]],
 
        [[ 0, 

: 

In [42]:
# model = ultralytics_model.model
# model = model.cuda()
dummy_input = torch.randn(1, 3, 416, 416, device='cuda')
best = "C:/Users/User/Desktop/InsectData/runs/detect/train36/weights/best.pt"
torch.onnx.export(best, dummy_input, "model.onnx")

AttributeError: 'str' object has no attribute 'training'

In [56]:
import torch

# 학습된 가중치 로드
# weights = 'C:/Users/User/Desktop/InsectData/runs/detect/train36/weights/best.pt'
# chkpt = torch.load(weights, map_location=torch.device('cpu'))
# model = ultralytics_model(cfg=chkpt['model'].yaml, ch=3, nc=chkpt['model'].nc)  # nc is the number of classes
# model.load_state_dict(chkpt['model'].float().state_dict())  # load model weights

model = yolo('C:/Users/User/Desktop/InsectData/runs/detect/train36/weights/best.pt')

# ONNX로 변환
dummy_input = torch.randn(1, 3, 416, 416, device='cuda')
output = model(dummy_input)
model = model.model.cuda()
torch.onnx.export(model, dummy_input, "model.onnx")
print(output.shape)


11.0ms
c:\Users\User\anaconda3\envs\Dbug\lib\site-packages\ultralytics\nn\modules\head.py:50: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif self.dynamic or self.shape != shape:
c:\Users\User\anaconda3\envs\Dbug\lib\site-packages\torch\onnx\symbolic_helper.py:346: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 9. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
We recommend using opset 11 and above for models using this operator. 
  wa

AttributeError: 'list' object has no attribute 'shape'

In [15]:
import onnx

# ONNX 모델 로드
model = onnx.load('C:/Users/User/Desktop/InsectData/model.onnx')

# 입력 레이어 출력
print('Model Input Layer:')
for input in model.graph.input:
    print(input.name, end=': ')
    # 레이어의 형상 출력
    shape = [dim.dim_value for dim in input.type.tensor_type.shape.dim]
    print(shape)


Model Input Layer:
input.1: [1, 3, 416, 416]


In [72]:
import cv2
import numpy as np
import onnxruntime

classes = []

# 클래스 라벨 불러오기
with open("C:/Users/User/Desktop/InsectData/ConvertData/HighDefinition_data/labels/classes.txt", "r") as f:
    classes = [line.strip() for line in f.readlines()]

# ONNX 런타임 세션 생성
sess = onnxruntime.InferenceSession("C:/Users/User/Desktop/InsectData/model.onnx")

# 이미지 불러오기
image = cv2.imread("C:/Users/User/Desktop/InsectData/Data/Training/rawData/TS1/PtecticusTenebrifer/Caterpillar/HighDefinition/Capture_20211115_15_27_37.jpg")
image = cv2.resize(image, None, fx=0.4, fy=0.4)
height, width, channels = image.shape
colors = np.random.uniform(0, 255, 3)

# 이미지 전처리
blob = cv2.dnn.blobFromImage(image, 0.00392, (416, 416), (0, 0, 0), swapRB=True, crop=False)
blob = blob.transpose((0, 1, 2, 3))  # ONNX는 CHW가 아니라 HWC 포맷을 기대합니다

# 모델 실행 및 출력 얻기
input_name = sess.get_inputs()[0].name
output_name = sess.get_outputs()[0].name
outs = sess.run([output_name],{input_name: blob})

print(input_name)
print(output_name)
print(np.array(outs).shape)

for i, out in enumerate(outs):
    print(f"Output node {i} shape: {out.shape}")
    print(out)

# 결과 처리
class_ids = []
confidences = []
boxes = []

class_ids = []
confidences = []
boxes = []

# 각 출력 노드에 대해 반복
for out in outs:
    # 첫 번째 차원(1)은 배치 크기를 나타내므로 우리는 이를 무시할 수 있습니다.
    # 모든 그리드 셀에 대해 순회합니다.
    for grid in out[0]:
        # 바운딩 박스의 x, y 좌표, 너비, 높이, 그리고 객체 존재 확률을 추출합니다.
        center_x, center_y, w, h, objectness = grid[:5]

        # 객체 존재 확률이 0.5보다 크면, 해당 그리드 셀에 대한 예측을 저장합니다.
        if objectness > 0.1:
            # 이미지의 크기에 따라 바운딩 박스의 좌표와 크기를 스케일링합니다.
            center_x = int(center_x * image.shape[1])
            center_y = int(center_y * image.shape[0])
            w = int(w * image.shape[1])
            h = int(h * image.shape[0])

            # 바운딩 박스의 좌표를 계산합니다 (YOLO는 바운딩 박스의 중심 좌표를 예측하므로, 우리는 이를 바운딩 박스의 좌측 상단 좌표로 변환해야 합니다).
            x = int(center_x - w / 2)
            y = int(center_y - h / 2)

            boxes.append([x, y, w, h])
            confidences.append(float(objectness))

            # 객체의 클래스 ID를 찾기 위해, 나머지 값을 확률로 간주하고 이 중에서 가장 높은 확률을 가진 클래스를 선택합니다.
            # 나머지 값을 확률로 간주하고 이 중에서 가장 높은 확률을 가진 클래스를 선택합니다.
            class_probabilities = grid[5:]
            class_id = np.argmax(class_probabilities)
            class_ids.append(class_id)
            # classes 리스트의 길이를 초과하지 않는지 확인합니다.
            # if class_id < len(classes):
            #     class_ids.append(class_id)
            # else:
            #     print(f"Warning: Predicted class id {class_id} is out of range of classes list with length {len(classes)}. Ignoring this box.")


# for out in outs:
#     for detection in out:
#         scores = detection[5:]
#         class_id = np.argmax(scores)
#         confidence = scores[class_id]
#         if confidence > 0.5:
#             # Object detected
#             center_x = int(detection[0] * width)
#             center_y = int(detection[1] * height)
#             w = int(detection[2] * width)
#             h = int(detection[3] * height)
#             # 좌표
#             x = int(center_x - w / 2)
#             y = int(center_y - h / 2)
#             boxes.append([x, y, w, h])
#             confidences.append(float(confidence))
#             class_ids.append(class_id)

# Non-Maxima Suppression 사용하여 겹치는 박스 제거
if boxes and confidences:  # 리스트가 비어 있지 않은지 확인
    indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
    print(indexes)
else:
    indexes = []

# 감지된 객체에 바운딩 박스와 레이블 그리기
font = cv2.FONT_HERSHEY_PLAIN
for i in range(len(boxes)):
    if i in indexes:
        x, y, w, h = boxes[i]
        label = str(class_ids[i])
        color = colors[0]
        cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)
        cv2.putText(image, label, (x, y + 30), font, 3, color, 3)
cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


input.1
420
(1, 1, 5, 3549)
Output node 0 shape: (1, 5, 3549)
[[[     7.9263      19.316      30.172 ...      343.31      372.69      395.38]
  [      5.292      4.8183      12.656 ...      372.76      376.34      395.04]
  [      13.83      36.187      57.525 ...       152.6      144.99      114.26]
  [     9.8277      10.043      26.687 ...      196.96      183.07      158.32]
  [          0           0           0 ...  8.9407e-08  1.4901e-07  5.9605e-08]]]
[2 0 1]


In [ ]:
import cv2
import numpy as np

onnx_model = "C:/Users/User/Desktop/InsectData/model.onnx"
net = cv2.dnn.readNetFromONNX(onnx_model)

image = cv2.imread("C:/Users/User/Desktop/InsectData/Data/Training/rawData/TS1/PtecticusTenebrifer/Caterpillar/Cam3/Capture_20211109_15_49_04.jpg")



In [18]:
import cv2
import numpy as np

# ONNX 모델 로드
net = cv2.dnn.readNetFromONNX("C:/Users/User/Desktop/InsectData/runs/detect/train31/weights/best.onnx")

classes = []
with open("C:/Users/User/Desktop/InsectData/ConvertData/HighDefinition_data/labels/classes.txt", "r") as f:
    classes = [line.strip() for line in f.readlines()]

colors = np.random.uniform(0, 255, size=(len(classes), 3))

# 이미지 로드
image = cv2.imread("C:/Users/User/Desktop/InsectData/Data/Training/rawData/TS1/PtecticusTenebrifer/Caterpillar/Cam3/Capture_20211109_15_49_04.jpg")

# 이미지 크기 조정
image = cv2.resize(image, (640, 640))

blob = cv2.dnn.blobFromImage(image, 1.0/255.0, (416, 416), (0, 0, 0), swapRB=True, crop=False)

net.setInput(blob)
outs = net.forward()

class_ids = []
confidences = []
boxes = []

for out in outs:
    for detection in out:
        scores = detection[5:]
        class_id = np.argmax(scores)
        confidence = scores[class_id]

        # 신뢰도 임계값 설정 (예: 0.5)
        if confidence > 0.5:
            center_x = int(detection[0] * image.shape[1])
            center_y = int(detection[1] * image.shape[0])
            w = int(detection[2] * image.shape[1])
            h = int(detection[3] * image.shape[0])

            x = int(center_x - w / 2)
            y = int(center_y - h / 2)

            boxes.append([x, y, w, h])
            confidences.append(float(confidence))
            class_ids.append(class_id)

indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
font = cv2.FONT_HERSHEY_PLAIN

for i in range(len(boxes)):
    if i in indexes:
        x, y, w, h = boxes[i]
        label = str(classes[class_ids[i]])
        color = colors[i]
        cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)
        cv2.putText(image, label, (x, y + 30), font, 3, color, 3)

cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\layers\reshape_layer.cpp:150: error: (-1:Backtrace) Can't infer a dim denoted by -1 in function 'cv::dnn::computeShapeByReshapeMask'


In [13]:
import cv2
import numpy as np

# ONNX 모델 로드
net = cv2.dnn.readNetFromONNX("C:/Users/User/Desktop/InsectData/model.onnx")

classes = []
with open("C:/Users/User/Desktop/InsectData/ConvertData/HighDefinition_data/labels/classes.txt", "r") as f:
    classes = [line.strip() for line in f.readlines()]

colors = np.random.uniform(0, 255, size=(len(classes), 3))

# 이미지 로드
image = cv2.imread("C:/Users/User/Desktop/InsectData/Data/Training/rawData/TS1/PtecticusTenebrifer/Caterpillar/Cam3/Capture_20211109_15_49_04.jpg")

# 이미지 크기 조정
image = cv2.resize(image, (640, 640))

blob = cv2.dnn.blobFromImage(image, 1/255, (640, 640), (0, 0, 0), swapRB=True, crop=False)

net.setInput(blob)
outs = net.forward()

class_ids = []
confidences = []
boxes = []

for out in outs:
    for detection in out:
        scores = detection[5:]
        class_id = np.argmax(scores)
        confidence = scores[class_id]

        # 신뢰도 임계값 설정 (예: 0.5)
        if confidence > 0.5:
            center_x = int(detection[0] * image.shape[1])
            center_y = int(detection[1] * image.shape[0])
            w = int(detection[2] * image.shape[1])
            h = int(detection[3] * image.shape[0])

            x = int(center_x - w / 2)
            y = int(center_y - h / 2)

            boxes.append([x, y, w, h])
            confidences.append(float(confidence))
            class_ids.append(class_id)

indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
font = cv2.FONT_HERSHEY_PLAIN

for i in range(len(boxes)):
    if i in indexes:
        x, y, w, h = boxes[i]
        label = str(classes[class_ids[i]])
        color = colors[i]
        cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)
        cv2.putText(image, label, (x, y + 30), font, 3, color, 3)

cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20221220::ONNXImporter::handleNode'
> Node [NonZero@ai.onnx]:(onnx_node!NonZero_223) parse error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:375: error: (-215:Assertion failed) (bool)layer in function 'cv::dnn::dnn4_v20221220::runLayer'
> 

In [28]:
import cv2
import numpy as np

# ONNX 모델 로드
net = cv2.dnn.readNetFromONNX("C:/Users/User/Desktop/InsectData/model.onnx")
classes = []

with open("C:/Users/User/Desktop/InsectData/ConvertData/HighDefinition_data/labels/classes.txt", "r") as f:
    classes = [line.strip() for line in f.readlines()]
layer_names = net.getLayerNames()

print(type(layer_names))
print(layer_names)

output_layers = [layer_names[i[0]] for i in net.getUnconnectedOutLayers()]


colors = np.random.uniform(0, 255, size=(len(classes), 3))

# 이미지 로드 및 전처리
image = cv2.imread("C:/Users/User/Desktop/InsectData/Data/Training/rawData/TS1/PtecticusTenebrifer/Caterpillar/Cam3/Capture_20211109_15_49_04.jpg")
image = cv2.resize(img, None, fx=0.4, fy=0.4)
blob = cv2.dnn.blobFromImage(image, 1/255, (640, 640), (0, 0, 0), swapRB=True, crop=False)

net.setInput(blob)
# outs = net.forward(output_layers)

# print(type(outs))
# print(outs)
# class_ids = []
# confidences = []
# boxes = []

# for out in outs:
#     for detection in out:
#         # 감지 결과에서 bounding box와 클래스 ID, 신뢰도 추출
#         scores = detection[5:]
#         classID = np.argmax(scores)
#         confidence = scores[classID]
        
#         # 신뢰도 임계값 설정 (예: 0.5)
#         if confidence > 0.5:
#             center_x = int(detection[0] * width)
#             center_y = int(detection[1] * height)
#             w = int(detection[2] * width)
#             h = int(detection[3] * height)

#             x = int(center_x - w / 2)
#             y = int(center_y - h / 2)
#             boxes.append([x, y, w, h])
#             confidences.append(float(confidence))
#             class_ids.append(classID)

# indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.4, 0.4)
# font = cv2.FONT_HERSHEY_PLAIN

# for i in range(len(boxes)):
#     if i in indexes:
#         w, y, w, h = boxes[i]
#         class_name = classes[class_ids[i]]
#         label = f"{class_name} {confidences[i]:.2f}"
#         color = colors[class_ids[i]]

#         cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)
#         cv2.putText(image, label, (x, y + 30), font, 3, color, 3)

# # 결과 이미지 표시
# cv2.imshow("Image", image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

<class 'tuple'>
('onnx_node!Conv_0', 'onnx_node!Sigmoid_1', 'onnx_node!Mul_2', 'onnx_node!Conv_3', 'onnx_node!Sigmoid_4', 'onnx_node!Mul_5', 'onnx_node!Conv_6', 'onnx_node!Sigmoid_7', 'onnx_node!Mul_8', 'onnx_node!Split_9', 'onnx_node!Conv_10', 'onnx_node!Sigmoid_11', 'onnx_node!Mul_12', 'onnx_node!Conv_13', 'onnx_node!Sigmoid_14', 'onnx_node!Mul_15', 'onnx_node!Add_16', 'onnx_node!Concat_17', 'onnx_node!Conv_18', 'onnx_node!Sigmoid_19', 'onnx_node!Mul_20', 'onnx_node!Conv_21', 'onnx_node!Sigmoid_22', 'onnx_node!Mul_23', 'onnx_node!Conv_24', 'onnx_node!Sigmoid_25', 'onnx_node!Mul_26', 'onnx_node!Split_27', 'onnx_node!Conv_28', 'onnx_node!Sigmoid_29', 'onnx_node!Mul_30', 'onnx_node!Conv_31', 'onnx_node!Sigmoid_32', 'onnx_node!Mul_33', 'onnx_node!Add_34', 'onnx_node!Conv_35', 'onnx_node!Sigmoid_36', 'onnx_node!Mul_37', 'onnx_node!Conv_38', 'onnx_node!Sigmoid_39', 'onnx_node!Mul_40', 'onnx_node!Add_41', 'onnx_node!Concat_42', 'onnx_node!Conv_43', 'onnx_node!Sigmoid_44', 'onnx_node!Mul_45'

IndexError: invalid index to scalar variable.

In [13]:
from PIL import Image
with Image.open('C:/Users/User/Desktop/InsectData/runs/detect/predict/Capture_20211115_15_26_51.jpg') as pred_image:
    pred_image.show()